version: '3.9'

services:

  server:
    image: backend
    container_name: 'cloud-service-backend'
    build: ./
    ports:
      - "5500:5500"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/cloudservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Gallavich18&
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:mysql://database:3306/cloudservice
      SPRING_LIQUIBASE_USER: root
      SPRING_LIQUIBASE_PASSWORD: Gallavich18&

  database:
    image: mysql
    container_name: 'mysqlData'
    volumes:
      - /mysqlData:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: Gallavich18&
      MYSQL_ROOT_PASSWORD: Gallavich18&
      MYSQL_DATABASE: cloudservice
    ports:
      - "3306:3306"